# End-To-End Example: Data Analysis of iSchool Classes

In this end-to-end example we will perform a data analysis in Python Pandas we will attempt to answer the following questions:

- What percentage of the schedule are undergrad (course number 500 or lower)?
- What undergrad classes are on Friday? or at 8AM?

Things we will demonstrate:

- `read_html()` for basic web scraping
- dealing with 5 pages of data
- `append()` multiple `DataFrames` together
- Feature engineering (adding a column to the `DataFrame`)

The iSchool schedule of classes can be found here: https://ischool.syr.edu/classes

In [2]:
import pandas as pd

# this turns off warning messages
import warnings
warnings.filterwarnings('ignore')

In [3]:
# just figure out how to get the data
website = 'https://ischool.syr.edu/classes/?page=1'
data = pd.read_html(website)
data[0]

,Course,Section,Class,Credits,Title,Instructor(s),Time,Day,Room(s)
0,GET300,M001,37202,3.0,Enterprise Data Analysis,Michael A Leonardo,5:15pm - 8:05pm,M,Hinds Hall 010
1,GET302,M001,37133,3.0,Global Financial Sys Arch,Frank Jr Marullo,5:00pm - 7:45pm,Tu,Hinds Hall 011
2,GET433,M001,37152,3.0,Multi-tier App. Development,P Douglas Taber,11:00am - 12:20pm,TuTh,Hinds Hall 013
3,GET487,M001,41408,3.0,Global Tech,Jeffrey Fouts,12:00am - 12:00am,NaN,Online
4,GET602,M001,37134,3.0,Global Financial Sys Arch,Frank Jr Marullo,5:00pm - 7:45pm,Tu,Hinds Hall 011
5,GET687,M801,37219,3.0,Global Tech,Jeffrey Fouts,12:00am - 12:00am,NaN,Online
6,IDS401,M001,41115,3.0,What's the Big Idea?,Michael A D'Eredita,5:00pm - 7:50pm,Tu,Hinds Hall 018
7,IDS403,M001,37093,1.0,Startup Sandbox,John DuRoss Liddy,2:15pm - 5:05pm,F,Syracuse Technology Garden
8,IDS460,M002,41735,3.0,Entretech - NYC,John DuRoss Liddy,12:00am - 12:00am,NaN,NaN
9,IDS460,M003,41736,3.0,Spring Break in Silicon Valley,John DuRoss Liddy,12:00am - 12:00am,NaN,NaN
10,IDS460,M004,41882,3.0,Entretech - Chicago,John DuRoss Liddy,12:00am - 12:00am,NaN,NaN
11,IDS660,M002,41738,3.0,Entretech - NYC,John DuRoss Liddy,12:00am - 12:00am,NaN,NaN
12,IDS660,M003,41739,3.0,Spring Break in Silicon Valley,John DuRoss Liddy,12:00am - 12:00am,NaN,NaN
13,IDS660,M004,41909,3.0,Entretech - Chicago,NaN,12:00am - 12:00am,NaN,NaN
14,IST101,M001,37194,1.0,First-Year Forum,Julie Walas Huynh,11:40am - 12:35pm,M,Hinds Hall 120
15,IST195,M001,37040,3.0,Information Technologies,Jeff Rubin,9:30am - 10:25am,MW,Huntington Beard Crouse Giff
16,IST195,M003,37110,3.0,LAB: Information Technologies,Jeff Rubin,9:30am - 10:25am,F,Hinds Hall 010
17,IST195,M004,37111,3.0,LAB: Information Technologies,Jeff Rubin,10:35am - 11:30am,F,Hinds Hall 010
18,IST195,M005,37112,3.0,LAB: Information Technologies,Jeff Rubin,11:40am - 12:35pm,F,Hinds Hall 010
19,IST195,M006,37113,3.0,LAB: Information Technologies,Jeff Rubin,12:45pm - 1:40pm,F,Hinds Hall 010
20,IST195,M007,37114,3.0,LAB: Information Technologies,Jeff Rubin,1:50pm - 2:45pm,F,Hinds Hall 010
21,IST195,M008,37119,3.0,LAB: Information Technologies,Jeff Rubin,2:55pm - 3:50pm,F,Hinds Hall 010
22,IST195,M002,37168,3.0,LAB: Information Technologies,Jeff Rubin,8:25am - 9:20am,F,Hinds Hall 010
23,IST233,M001,37062,3.0,Intro to Computer Networking,S Bruce Boardman,12:45pm - 1:40pm,MW,Hall of Languages 207
24,IST233,M008,37102,3.0,Intro to Computer Networking,Jeffrey T Girard,5:00pm - 6:20pm,TuTh,Hinds Hall 027 Hinds Hall 117
25,IST233,M003,37115,3.0,LAB: Intro to Computer Networking,S Bruce Boardman,10:35am - 11:30am,F,Hinds Hall 027
26,IST233,M004,37116,3.0,LAB: Intro to Computer Networking,S Bruce Boardman,11:40am - 12:35pm,F,Hinds Hall 027
27,IST233,M005,37117,3.0,LAB: Intro to Computer Networking,S Bruce Boardman,12:45pm - 1:40pm,F,Hinds Hall 027
28,IST233,M006,37118,3.0,LAB: Intro to Computer Networking,S Bruce Boardman,1:50pm - 2:45pm,F,Hinds Hall 027
29,IST256,M001,37188,3.0,Appl.Prog.For Information Syst,Michael Fudge,3:45pm - 5:05pm,M,Heroy Geology Building Aud
30,IST256,M002,40684,3.0,Appl.Prog.For Information Syst,Deborah L Nosky,9:30am - 10:50am,Th,Hinds Hall 011
31,IST256,M003,40685,3.0,Appl.Prog.For Information Syst,Angela Usha Ramnarine-Rieks,3:45pm - 5:05pm,W,FALK ROOM 201
32,IST256,M004,40686,3.0,Appl.Prog.For Information Syst,Angela Usha Ramnarine-Rieks,12:30pm - 1:50pm,Th,Life Science Building 214
33,IST256,M005,40687,3.0,Appl.Prog.For Information Syst,Wade Stringer,5:00pm - 6:20pm,Th,Hinds Hall 117
34,IST256,M006,40688,3.0,Appl.Prog.For Information Syst,Wade Stringer,9:30am - 10:50am,W,Hinds Hall 011
35,IST256,M007,41229,3.0,Appl.Prog.For Information Syst,Nick Lyga,5:15pm - 6:35pm,MW,Heroy Geology Building 113
36,IST256,M008,41760,3.0,Appl.Prog.For Information Syst,Avinash Kadaji,8:00am - 9:20am,W,Hinds Hall 018
37,IST256,M009,42235,3.0,Appl.Prog.For Information Syst,Deborah L Nosky,2:15pm - 3:35pm,W,Hinds Hall 018
38,IST263,M001,37066,3.0,Intro to Front-End Web Dev,Christian A Kirkegaard,11:00am - 12:20pm,TuTh,Hinds Hall 111
39,IST263,M002,37106,3.0,Intro to Front-End Web Dev,Christian A Kirkegaard,8:00am - 9:20am,TuTh,Hinds Hall 018
40,IST263,M005,37165,3.0,Intro to Front-End Web Dev,Jennifer Sonne,11:00am - 12:20pm,TuTh,Hinds Hall 117
41,IST300,M001,37046,3.0,IM&T Support Practicum,Christopher Perrello,12:00am - 12:00am,NaN,NaN
42,IST300,M002,37195,3.0,Digital Campaign Strat/Analyti,Michael Clarke,3:30pm - 4:50pm,TuTh,Hinds Hall 011
43,IST300,M004,42111,3.0,"IOT-SpyTool, Hackers Playgroun",Christopher Sedore,5:00pm - 7:50pm,Th,Bowne Hall 105
44,IST323,M001,37076,3.0,Intro to Information Security,Christopher Croad,2:15pm - 5:05pm,W,Hinds Hall 027 Hinds Hall 117
45,IST323,M002,37090,3.0,Intro to Information Security,Joon S. Park,3:45pm - 5:05pm,MW,Hinds Hall 021 Hinds Hall 117
46,IST323,M003,37161,3.0,Intro to Information Security,James Enwright,6:45pm - 8:05pm,MW,Hinds Hall 013
47,IST335,M001,37047,3.0,Intro/Info Based Organizations,Michael A D'Eredita,3:30pm - 4:50pm,Tu,CH010
48,IST335,M003,37071,3.0,Intro/Info Based Organizations,Michael A D'Eredita,12:45pm - 2:05pm,F,Hinds Hall 111
49,IST335,M004,37100,3.0,Intro/Info Based Organizations,Michael A D'Eredita,2:15pm - 3:35pm,F,Hinds Hall 111

In [4]:
# let's generate links to the other pages
website = 'https://ischool.syr.edu/classes/?page='
for i in range(1,6):
    link = website + str(i)
    print(link)

https://ischool.syr.edu/classes/?page=1
https://ischool.syr.edu/classes/?page=2
https://ischool.syr.edu/classes/?page=3
https://ischool.syr.edu/classes/?page=4
https://ischool.syr.edu/classes/?page=5

In [5]:
# let's read them all and append them to a single data frame

website = 'https://ischool.syr.edu/classes/?page='
classes = pd.DataFrame() #  (columns = ['Course','Section','ClassNo','Credits','Title','Instructor','Time','Days','Room'])

for i in range(1,6):
    link = website + str(i)
    data = pd.read_html(website  + str(i))    
    classes = classes.append(data[0], ignore_index=True)
    
classes.sample(5)

,Course,Section,Class,Credits,Title,Instructor(s),Time,Day,Room(s)
184,IST664,M001,37178,3.0,Natural Language Processing,Lu Xiao,2:15pm - 5:05pm,M,Hinds Hall 027
72,IST359,M002,37073,3.0,Intro to Data Base Mgmt Systs,Trudi L Porter,5:00pm - 7:45pm,Tu,Hinds Hall 010
25,IST233,M003,37115,3.0,LAB: Intro to Computer Networking,S Bruce Boardman,10:35am - 11:30am,F,Hinds Hall 027
157,IST625,M002,37183,3.0,Enterprise Risk Management,Frank Jr Marullo,5:15pm - 8:05pm,W,Hinds Hall 117
207,IST719,M001,37142,3.0,Information Visualization,Joseph P. Brusa,5:15pm - 8:05pm,M,Hinds Hall 027

In [6]:
## let's set the columns

website = 'https://ischool.syr.edu/classes/?page='
classes = pd.DataFrame() 

for i in range(1,6):
    link = website + str(i)
    data = pd.read_html(website  + str(i))    
    classes = classes.append(data[0], ignore_index=True)
    
classes.columns = ['Course','Section','ClassNo','Credits','Title','Instructor','Time','Days','Room']

classes.sample(5)

,Course,Section,ClassNo,Credits,Title,Instructor,Time,Days,Room
195,IST687,M402,41792,3.0,Applied Data Science,NaN,7:00pm - 8:30pm,Tu,Online
65,IST346,M003,42130,3.0,Info Tech Mgmt&Administration,Lauren J Hardee-Chase,3:45pm - 5:05pm,MW,Hinds Hall 013
53,IST344,M004,37053,3.0,Info Reporting & Presentation,Bruce Kingma,9:30am - 10:50am,TuTh,Hinds Hall 018
17,IST195,M004,37111,3.0,LAB: Information Technologies,Jeff Rubin,10:35am - 11:30am,F,Hinds Hall 010
179,IST659,M402,41788,3.0,Data Admin Concepts & Db Mgmt,Dale Thompson,7:00pm - 8:30pm,Tu,Online

In [11]:
## this is good stuff. Let's make a function out of it for simplicity

def get_ischool_classes():
    website = 'https://ischool.syr.edu/classes/?page='
    classes = pd.DataFrame() 

    for i in range(1,6):
        link = website + str(i)
        data = pd.read_html(website  + str(i))    
        classes = classes.append(data[0], ignore_index=True)
    
    classes.columns = ['Course','Section','ClassNo','Credits','Title','Instructor','Time','Days','Room']

    return classes
 
# main program 
classes = get_ischool_classes()

In [12]:
# undergrad classes are 0-499, grad classes are 500 and up but we don't have course numbers!!!! So we must engineer them.

classes['Course'].str[0:3].sample(5)
classes['Course'].str[3:].sample(5)

5      687
144    618
183    663
97     486
121    604
Name: Course, dtype: object

In [9]:
# make the subject and number columns
classes['Subject'] = classes['Course'].str[0:3]
classes['Number'] = classes['Course'].str[3:]
classes.sample(5)

,Course,Section,ClassNo,Credits,Title,Instructor,Time,Days,Room,Subject,Number
74,IST359,M004,37121,3.0,Intro to Data Base Mgmt Systs,Chad Aaron Harper,2:00pm - 3:20pm,TuTh,Hinds Hall 027 Hinds Hall 111,IST,359
83,IST425,M002,37215,3.0,Enterprise Risk Management,James Enwright,5:00pm - 7:50pm,Tu,Sims Hall 241,IST,425
126,IST605,M405,41805,3.0,Reference& Info Literacy Svces,Amanda Bucher Albert,9:00pm - 10:30pm,Tu,Online,IST,605
135,IST614,M400,37220,3.0,Mngmt Prncpls for Info Profess,John P. Stinnett,7:00pm - 8:30pm,Tu,Online,IST,614
197,IST700,M800,37193,3.0,Leading IT: Transforming the E,Scott A Bernard,12:00am - 12:00am,NaN,Online,IST,700

In [36]:
# and finally we can create the column we need!
classes['Type'] = ''
classes['Type'][classes['Number'] < '500'] = 'UGrad'
classes['Type'][classes['Number'] >= '500'] = 'Grad'

classes.sample(5)

,Course,Section,ClassNo,Credits,Title,Instructor,Time,Days,Room,Subject,Number,UG,Type
113,IST600,M800,37113,1.0,IT Auditing,Thomas J Wood,12:00am - 12:00am,NaN,Online,IST,600,N,Grad
1,GET302,M001,37049,3.0,Global Financial Sys Arch,Frank Jr Marullo,5:15pm - 8:00pm,M,Hinds Hall 021,GET,302,Y,UGrad
182,IST718,M801,37082,3.0,Advanced Information Analytics,Gary E Krudys,12:00am - 12:00am,NaN,Online,IST,718,N,Grad
193,IST754,M001,37065,3.0,Telecom Final Project,Lee H Badman,9:30am - 12:15pm,W,Hinds Hall 117,IST,754,N,Grad
69,IST425,M001,36950,3.0,Enterprise Risk Management,Michael Larche,5:15pm - 6:35pm,MW,Slocum 104,IST,425,Y,UGrad

In [44]:
# the entire program to retrieve the data and setup the columns looks like this:

# main program 
classes = get_ischool_classes()
classes['Subject'] = classes['Course'].str[0:3]
classes['Number'] = classes['Course'].str[3:]
classes['Type'] = ''
classes['Type'][classes['Number'] < '500'] = 'UGrad'
classes['Type'][classes['Number'] >= '500'] = 'Grad'

In [45]:
# let's fins the number of grad / undergrad courses
classes['Type'].value_counts()

# more grad classes than undergrad

Grad     116
UGrad     95
Name: Type, dtype: int64

In [46]:
# how many undergrad classes on a Friday?
friday = classes[ (classes['Type'] == 'UGrad') & (classes['Days'].str.find('F')>=0 ) ]
friday

,Course,Section,ClassNo,Credits,Title,Instructor,Time,Days,Room,Subject,Number,Type
3,GET400,M002,37081,3.0,Global Consulting Challenges,Jason Dedrick,10:35am - 1:10pm,F,Hinds Hall 018,GET,400,UGrad
11,IDS402,M001,37004,3.0,Idea2Startup,Michael A D'Eredita,9:30am - 12:15pm,F,Hinds Hall 011,IDS,402,UGrad
12,IDS403,M001,37002,1.0,Startup Sandbox,John DuRoss Liddy,10:00am - 12:50pm,F,Syracuse Technology Garden,IDS,403,UGrad
13,IDS403,M002,41254,1.0,Startup Sandbox,John DuRoss Liddy,1:00pm - 3:50pm,F,Syracuse Technology Garden,IDS,403,UGrad
16,IST195,M003,37021,3.0,LAB: Information Technologies,Jeff Rubin,9:30am - 10:25am,F,Hinds Hall 010,IST,195,UGrad
17,IST195,M004,37022,3.0,LAB: Information Technologies,Jeff Rubin,10:35am - 11:30am,F,Hinds Hall 010,IST,195,UGrad
18,IST195,M005,37023,3.0,LAB: Information Technologies,Jeff Rubin,11:40am - 12:35pm,F,Hinds Hall 010,IST,195,UGrad
19,IST195,M006,37024,3.0,LAB: Information Technologies,Jeff Rubin,12:45pm - 1:40pm,F,Hinds Hall 010,IST,195,UGrad
20,IST195,M007,37025,3.0,LAB: Information Technologies,Jeff Rubin,1:50pm - 2:45pm,F,Hinds Hall 010,IST,195,UGrad
21,IST195,M008,37031,3.0,LAB: Information Technologies,Jeff Rubin,2:55pm - 3:50pm,F,Hinds Hall 010,IST,195,UGrad
22,IST195,M002,37107,3.0,LAB: Information Technologies,Jeff Rubin,8:25am - 9:20am,F,Hinds Hall 010,IST,195,UGrad
25,IST233,M003,37027,3.0,LAB: Intro to Computer Networking,David J Molta,10:35am - 11:30am,F,Hinds Hall 027,IST,233,UGrad
26,IST233,M004,37028,3.0,LAB: Intro to Computer Networking,David J Molta,11:40am - 12:35pm,F,Hinds Hall 027,IST,233,UGrad
27,IST233,M005,37029,3.0,LAB: Intro to Computer Networking,David J Molta,12:45pm - 1:40pm,F,Hinds Hall 027,IST,233,UGrad
28,IST233,M006,37030,3.0,LAB: Intro to Computer Networking,David J Molta,1:50pm - 2:45pm,F,Hinds Hall 027,IST,233,UGrad
29,IST233,M007,40344,3.0,LAB: Intro to Computer Networking,David J Molta,2:55pm - 3:50pm,F,Hinds Hall 027,IST,233,UGrad
31,IST256,M001,40238,3.0,Appl.Prog.For Information Syst,Michael Fudge Avinash Kadaji Deborah L Nosky...,8:00am - 9:20am,WF,School of Management 007,IST,256,UGrad
41,IST335,M002,36937,3.0,Intro/Info Based Organizations,Michael A D'Eredita,12:45pm - 2:05pm,WF,Hinds Hall 011,IST,335,UGrad

In [47]:
# let's get rid of those pesky LAB sections!!!
# how many undergrad classes on a Friday?
friday_no_lab = friday[ ~friday['Title'].str.startswith('LAB:')]
friday_no_lab

,Course,Section,ClassNo,Credits,Title,Instructor,Time,Days,Room,Subject,Number,Type
3,GET400,M002,37081,3.0,Global Consulting Challenges,Jason Dedrick,10:35am - 1:10pm,F,Hinds Hall 018,GET,400,UGrad
11,IDS402,M001,37004,3.0,Idea2Startup,Michael A D'Eredita,9:30am - 12:15pm,F,Hinds Hall 011,IDS,402,UGrad
12,IDS403,M001,37002,1.0,Startup Sandbox,John DuRoss Liddy,10:00am - 12:50pm,F,Syracuse Technology Garden,IDS,403,UGrad
13,IDS403,M002,41254,1.0,Startup Sandbox,John DuRoss Liddy,1:00pm - 3:50pm,F,Syracuse Technology Garden,IDS,403,UGrad
31,IST256,M001,40238,3.0,Appl.Prog.For Information Syst,Michael Fudge Avinash Kadaji Deborah L Nosky...,8:00am - 9:20am,WF,School of Management 007,IST,256,UGrad
41,IST335,M002,36937,3.0,Intro/Info Based Organizations,Michael A D'Eredita,12:45pm - 2:05pm,WF,Hinds Hall 011,IST,335,UGrad

In [48]:
# Looking for more classes to avoid? How about 8AM classes?
eight_am = classes[ classes['Time'].str.startswith('8:00am')]
eight_am

,Course,Section,ClassNo,Credits,Title,Instructor,Time,Days,Room,Subject,Number,Type
4,GET433,M001,37075,3.0,Multi-tier App. Development,P Douglas Taber,8:00am - 9:20am,TuTh,Hinds Hall 013,GET,433,UGrad
31,IST256,M001,40238,3.0,Appl.Prog.For Information Syst,Michael Fudge Avinash Kadaji Deborah L Nosky...,8:00am - 9:20am,WF,School of Management 007,IST,256,UGrad
33,IST263,M003,37015,3.0,Web Design and Mgmt,Joseph E Flateau,8:00am - 9:20am,MW,Hinds Hall 021,IST,263,UGrad
34,IST263,M002,37017,3.0,Web Design and Mgmt,Christian A Kirkegaard,8:00am - 9:20am,TuTh,Hinds Hall 018,IST,263,UGrad
54,IST352,M005,37068,3.0,Info Analysis of Org. Systems,Alexander Corsello,8:00am - 9:20am,MW,Hinds Hall 111,IST,352,UGrad
55,IST352,M006,37069,3.0,Info Analysis of Org. Systems,Alexander Corsello,8:00am - 9:20am,TuTh,Hinds Hall 117,IST,352,UGrad
58,IST359,M003,36986,3.0,Intro to Data Base Mgmt Systs,Deborah L Nosky,8:00am - 9:20am,TuTh,Hinds Hall 010 Hinds Hall 111,IST,359,UGrad